//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbArticuloBaja
    {
        public int IdArticulosBaja { get; set; }
        public Nullable<int> IdTipoMovimimiento { get; set; }
        public Nullable<int> IdArticuloBodega { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string NombreMedida { get; set; }
        public Nullable<decimal> TotalUnidades { get; set; }
        public string DescripciónArticuloBaja { get; set; }
        public Nullable<int> IdArticulo { get; set; }
    
        public virtual TbArticuloBodega TbArticuloBodega { get; set; }
        public virtual TbTipoMovimiento TbTipoMovimiento { get; set; }
    }
}
