//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbArticuloBodega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbArticuloBodega()
        {
            this.TbArticuloBaja = new HashSet<TbArticuloBaja>();
            this.TbMovimientoArticulo = new HashSet<TbMovimientoArticulo>();
        }
    
        public int IdArticuloBodega { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<int> IdMedida { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdColor { get; set; }
        public Nullable<int> IdTalla { get; set; }
        public string Existencia { get; set; }
        public Nullable<double> PrecioCompra { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> DescuentoMaximo { get; set; }
        public Nullable<int> IdCompra { get; set; }
    
        public virtual TbArticulo TbArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbArticuloBaja> TbArticuloBaja { get; set; }
        public virtual TbBodega TbBodega { get; set; }
        public virtual TbColor TbColor { get; set; }
        public virtual TbMarca TbMarca { get; set; }
        public virtual TbMedida TbMedida { get; set; }
        public virtual TbTalla TbTalla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbMovimientoArticulo> TbMovimientoArticulo { get; set; }
    }
}
