//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbArticulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbArticulo()
        {
            this.TbArticuloBodega = new HashSet<TbArticuloBodega>();
            this.TbDevoluciònVenta = new HashSet<TbDevoluciònVenta>();
            this.TbMovimientoArticulo = new HashSet<TbMovimientoArticulo>();
        }
    
        public int IdArticulo { get; set; }
        public string NombreArticulo { get; set; }
        public string Descripción { get; set; }
        public Nullable<int> IdSubCategoria { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual TbSubCategoria TbSubCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbArticuloBodega> TbArticuloBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbDevoluciònVenta> TbDevoluciònVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbMovimientoArticulo> TbMovimientoArticulo { get; set; }
    }
}
