//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbConfiguración
    {
        public int IdConfiguración { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string NombreTienda { get; set; }
        public string CofiguraciónDelLema { get; set; }
        public Nullable<decimal> ConfTelefono { get; set; }
        public string ConfDireccion { get; set; }
        public string ConfEncabezadoFactura { get; set; }
    
        public virtual TbUsuario TbUsuario { get; set; }
    }
}
