//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDevoluciònVenta
    {
        public int IdDevoluciònVenta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public string NoFactura { get; set; }
        public Nullable<System.DateTime> FechaDevoluciòn { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string DescripciònDevoluciòn { get; set; }
    
        public virtual TbArticulo TbArticulo { get; set; }
        public virtual TbUsuario TbUsuario { get; set; }
        public virtual TbVenta TbVenta { get; set; }
    }
}
