//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDetalleCompra
    {
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public int IdDetalleCompra { get; set; }
    
        public virtual TbCompra TbCompra { get; set; }
    }
}
