//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbMovimientoArticulo
    {
        public int IdMovimientoArticulo { get; set; }
        public Nullable<int> IdTipoMovimiento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdArticuloBodega { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> TotalMedida { get; set; }
        public string DescripciónMovimientoArticulo { get; set; }
        public Nullable<int> IdArticulo { get; set; }
    
        public virtual TbArticulo TbArticulo { get; set; }
        public virtual TbArticuloBodega TbArticuloBodega { get; set; }
        public virtual TbTipoMovimiento TbTipoMovimiento { get; set; }
    }
}
