//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbProveedor()
        {
            this.TbCompra = new HashSet<TbCompra>();
        }
    
        public int IdProveedor { get; set; }
        public string NombreEmpresa { get; set; }
        public string Dirección { get; set; }
        public string NombreConctato { get; set; }
        public Nullable<decimal> Tefonono { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbCompra> TbCompra { get; set; }
    }
}
