//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbRolUsuario
    {
        public int IdUsuario { get; set; }
        public Nullable<int> IdRol { get; set; }
    
        public virtual TbRol TbRol { get; set; }
        public virtual TbUsuario TbUsuario { get; set; }
    }
}
