//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaLitos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbVenta()
        {
            this.TbDevoluciònVenta = new HashSet<TbDevoluciònVenta>();
            this.TbDetalleVenta = new HashSet<TbDetalleVenta>();
        }
    
        public int IdVenta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdPromoción { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<bool> Anular { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public string NombreCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbDevoluciònVenta> TbDevoluciònVenta { get; set; }
        public virtual TbPromoción TbPromoción { get; set; }
        public virtual TbUsuario TbUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbDetalleVenta> TbDetalleVenta { get; set; }
    }
}
